data_loader:
  batch_size: 1
model:
  d_model: 512
  d_embed: 512
  max_len: 20480
  decoder:
    n_layer: 12
    n_head: 8
    d_ff: 2048
    feature_map:
      n_dims: 64
representation:
  num_tracks: 5
  resolution: 12
timing:
  resolution: 12
  max_shift: 2  # beats

seed: 0
train_data_path: /tsi/doctorants/ocifka/data/biab_midi/irbgen_2x1k5styles_v3/muspy_12ppq/train_split/train
training:
  num_epochs: 16
  ckpt_interval: 1
  log_interval: 200

  lr: 1.0e-4
  lr_scheduler:
    class: !!python/name:torch.optim.lr_scheduler.CosineAnnealingLR
    eta_min: 1.0e-5
    T_max: 87352  # 5522 * 16 - 1000
  warmup_steps: 1000

  feature_redraw_interval: 40

val_data_paths:
  val: /tsi/doctorants/ocifka/data/biab_midi/irbgen_2x1k5styles_v3/muspy_12ppq/train_split/val
  ival: /tsi/doctorants/ocifka/data/biab_midi/irbgen_2x1k5styles_v3/muspy_12ppq/train_split/ival
val_data_loader:
  batch_size: 8
